// Transitional map-only geocoding. Travel offer search lives exclusively in FastAPI Contract v1.
const BASE='https://serpapi.com/search.json'
export interface GeoPoint{name:string;lat:number;lng:number}
export async function geocodePlace(query:string):Promise<{lat:number;lng:number}|null>{const key=process.env.SERPAPI_API_KEY;if(!key)return null;const qs=new URLSearchParams({engine:'google_maps',q:query,hl:'iw',gl:'il',api_key:key});try{const res=await fetch(`${BASE}?${qs.toString()}`,{cache:'no-store'});if(!res.ok)return null;const data:any=await res.json();let gps=data?.place_results?.gps_coordinates;if(!gps)gps=(data?.local_results??[])[0]?.gps_coordinates;return gps&&typeof gps.latitude==='number'&&typeof gps.longitude==='number'?{lat:gps.latitude,lng:gps.longitude}:null}catch(e){console.error('geocodePlace error:',e);return null}}
export async function geocodePlaces(places:string[],destination:string):Promise<GeoPoint[]>{const unique=Array.from(new Set(places.map(p=>p.trim()).filter(Boolean))).slice(0,40);const out:(GeoPoint|null)[]=new Array(unique.length).fill(null);let idx=0;async function worker(){while(idx<unique.length){const cur=idx++;const name=unique[cur];const query=destination&&!name.includes(destination)?`${name}, ${destination}`:name;const gps=await geocodePlace(query);if(gps)out[cur]={name,...gps}}}await Promise.all(Array.from({length:Math.min(4,unique.length)},()=>worker()));return out.filter((x):x is GeoPoint=>x!==null)}
function esc(s:string){return(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
export function buildKml(points:GeoPoint[],mapName:string){const marks=points.map((p,i)=>`<Placemark><name>${esc(`${i+1}. ${p.name}`)}</name><Point><coordinates>${p.lng},${p.lat},0</coordinates></Point></Placemark>`).join('\n');return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${esc(mapName)}</name>${marks}</Document></kml>`}
export interface DayPoints{label:string;points:GeoPoint[]}
export function buildKmlByDays(days:DayPoints[],mapName:string){const folders=days.map((d)=>`<Folder><name>${esc(d.label)}</name>${d.points.map((p,i)=>`<Placemark><name>${esc(`${i+1}. ${p.name}`)}</name><description>${esc(`${d.label} - ${p.name}`)}</description><Point><coordinates>${p.lng},${p.lat},0</coordinates></Point></Placemark>`).join('')}</Folder>`).join('');return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${esc(mapName)}</name>${folders}</Document></kml>`}
